UnionStreet/Controllers/UnionStreetController.cs
using BuisnessObjects.UnionStreet;
using Implementation;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UnionStreet.Controllers
{
    //README.TXT
    //To Sortby - click on header index
    //Access buinsess logic project to get, post, put data on server.
    //DataAccessLayer project - to access database; used entity framework
    //BuisnessLogic - For additional filtering, logic - once data is returned from data access layer
    //BuisnessObjects - For models
    public class UnionStreetController : Controller
    {
        private UnionStreetBuisnessLogic BL;
        public UnionStreetController()
        {
            BL = new UnionStreetBuisnessLogic();
        }
        public ActionResult Index(string SortType, string currentSort)
        {
            if (currentSort == null || currentSort == "desc")
                currentSort = "asc";
            else
                currentSort = "desc";
            
            var lstDetails = BL.GetDetails(0, SortType, currentSort);
            return View(lstDetails);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Details model)
        {
            BL.Save(model);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int? detailId)
        {
            if (!detailId.HasValue)
                return HttpNotFound();
            var lstDetails = BL.GetDetails(detailId.Value, "Company", "asc");
            return View("Edit",lstDetails[0]);
        }

        [HttpPost]
        public ActionResult Edit(Details model)
        {
            BL.Save(model);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int detailId)
        {
            BL.Delete(detailId);
           return RedirectToAction("Index");
        }
    }
}

UnionStreet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

UnionStreet/Views/UnionStreet/Create.cshtml
@model BuisnessObjects.UnionStreet.Details

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
@using (Html.BeginForm("Create", "UnionStreet", FormMethod.Post))
{
    
<table>
    <tr>
        <td class="width:50px;">
            @Html.LabelFor(Item => Item.Company.CompanyName)
                    @Html.TextBoxFor(Item => Item.Company.CompanyName)
                </td>
                <td class="width:50px;">
                      @Html.LabelFor(Item => Item.Site.SiteName)
                    @Html.TextBoxFor(Item => Item.Site.SiteName)
                </td>
        </tr><tr>

                <td class="width:50px;">
                    @Html.LabelFor(Item => Item.MainSite,"True")
                    @Html.RadioButtonFor(Item => Item.MainSite,"True")
                    @Html.LabelFor(Item => Item.MainSite,"False")
                    @Html.RadioButtonFor(Item => Item.MainSite,"False")
                </td>
                <td class="width:50px;">
                      @Html.LabelFor(Item => Item.Notes)
                    @Html.TextBoxFor(Item => Item.Notes)
                </td>
            </tr><tr>
                 <td class="width:50px;">
                       @Html.LabelFor(Item => Item.PhoneNumber)
                    @Html.TextBoxFor(Item => Item.PhoneNumber)
                </td>
                <td class="width:50px;">
                      @Html.LabelFor(Item => Item.StartDate)
                    @Html.TextBoxFor(Item => Item.StartDate, new { @class=""})
                </td>
                </tr>
    <tr>
                 <td class="width:50px;">
                       @Html.LabelFor(Item => Item.EndDate)
                    @Html.TextBoxFor(Item => Item.EndDate)
                </td>
    </tr>
    <tr>
        <td>
           <input type="submit" name="Create" value="Save"/>
        </td>

    </tr>
</table>
}

UnionStreet/Views/UnionStreet/Edit.cshtml
@model BuisnessObjects.UnionStreet.Details
@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm("Edit", "UnionStreet", FormMethod.Post))
{
<table>
    <tr>
        <td>
            @Html.LabelFor(m=>m.Company.CompanyName)
            @Html.TextBoxFor(m=>m.Company.CompanyName)
            @Html.HiddenFor(m=>m.Company.CompanyName)
        </td>
         <td>
            @Html.LabelFor(m=>m.Site.SiteName)
            @Html.TextBoxFor(m=>m.Site.SiteName)
            @Html.HiddenFor(m=>m.Site.SiteName)
        </td>
         <td>
            @Html.LabelFor(m=>m.MainSite, "True")
            @Html.RadioButtonFor(m=>m.MainSite,"True")
             @Html.LabelFor(m=>m.MainSite, "False")
              @Html.RadioButtonFor(m=>m.MainSite,"False")
            @Html.HiddenFor(m=>m.MainSite)
        </td>
    </tr>
    <tr>
        <td>
            @Html.LabelFor(m=>m.Notes)
            @Html.TextBoxFor(m=>m.Notes)
            @Html.HiddenFor(m=>m.Notes)
        </td>
         <td>
            @Html.LabelFor(m=>m.PhoneNumber)
            @Html.TextBoxFor(m=>m.PhoneNumber)
            @Html.HiddenFor(m=>m.PhoneNumber)
        </td>
         <td>
            @Html.LabelFor(m=>m.StartDate)
            @Html.TextBoxFor(m=>m.StartDate)
            @Html.HiddenFor(m=>m.StartDate)
        </td>
    </tr>
    <tr>
        <td>
            @Html.LabelFor(m=>m.EndDate)
            @Html.TextBoxFor(m=>m.EndDate)
            @Html.HiddenFor(m=>m.EndDate)
        </td>

    </tr>
    <tr>
        <td>
            <input type="submit", name="Save" value="Save"/>
            @Html.HiddenFor(m=>m.DetailsId)
            @Html.HiddenFor(m=>m.Company.CompanyId)
            @Html.HiddenFor(m=>m.Site.Id)
        </td>

    </tr>

</table>
}

UnionStreet/Views/UnionStreet/Index.cshtml
@model List<BuisnessObjects.UnionStreet.Details>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<div>
 @Html.ActionLink("Create New", "Create")
</div>

<table>
    <thead>
         <tr>
                <td>
                    @Html.ActionLink("Company", "Index", new { currentSort=Model[0].CurrentSort, SortType="Company"})
                </td>
                <td>
                    @Html.ActionLink("Site", "Index", new { currentSort=Model[0].CurrentSort, SortType="Site"})
                </td>
                <td>
                    @Html.ActionLink("MainSite", "Index", new { currentSort=Model[0].CurrentSort, SortType="MainSite"})
                </td>
                <td>
                    @Html.ActionLink("Notes", "Index", new { currentSort=Model[0].CurrentSort, SortType="Notes"})
                </td>
                 <td>
                    @Html.ActionLink("PhoneNumber", "Index", new { currentSort=Model[0].CurrentSort, SortType="PhoneNumber"})
                </td>
                <td>
                    @Html.ActionLink("StartDate", "Index", new { currentSort=Model[0].CurrentSort, SortType="StartDate"})
                </td>
                 <td>
                    @Html.ActionLink("EndDate", "Index", new { currentSort=Model[0].CurrentSort, SortType="EndDate"})
                </td>
                <td>
                </td>
            </tr>
    </thead>
    <tbody>
        @foreach (var detail in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(Item => detail.Company.CompanyName)
                </td>
                <td>
                    @Html.DisplayFor(Item => detail.Site.SiteName)
                </td>
                <td>
                    @Html.DisplayFor(Item => detail.MainSite)
                </td>
                <td>
                    @Html.DisplayFor(Item => detail.Notes)
                </td>
                 <td>
                    @Html.DisplayFor(Item => detail.PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(Item => detail.StartDate)
                </td>
                 <td>
                    @Html.DisplayFor(Item => detail.EndDate)
                </td>
                 <td>
                    @Html.ActionLink("Edit", "Edit", new { detailId=detail.DetailsId})
                     @Html.ActionLink("Delete", "Delete", new { detailId=detail.DetailsId})
                </td>
            </tr>
        }
    </tbody>
</table>